name: atmosfer
description: Turkcell atmosfer project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.9.2
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  fluttertoast: ^8.2.1
  get: ^4.6.5
  lottie: ^2.3.2
  file_picker: ^5.2.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/data/
    - assets/animations/
